###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "susanne",
    "password":"laportyerin",
    "email":"jsantillanr1500@alumno.ipn.mx"

}

###
POST http://localhost:9000/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "annlaport23@gmail.com",
    "password":"susanne"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/635f55611d597a1fc1f7edcf HTTP/1.1


###
PUT http://localhost:9000/api/users/635f55e21d597a1fc1f7edd1 HTTP/1.1
Content-Type: application/json

{
    "name": "Laport Saelemaekers",
    "description": "Young man with deep blue hair",
    "abilitie":"he increase his resistance and force, and can control wolves"

}

###
DELETE http://localhost:9000/api/users/63801edfa1086e94cf4bffdd HTTP/1.1


###
POST http://localhost:9000/api/addpokemon HTTP/1.1
Content-Type: application/json

{
    "id": "745",
    "name": "lycanroc",
    "trainer":"637065d15f857fe5b0a8da69",
    "gender":"male"

}

###
GET http://localhost:9000/api/users/name/laport

###
GET http://localhost:9000/api/pokemon/63786a03f50bb07ea609e7a2

###
DELETE http://localhost:9000/api/pokemon/63801edda1086e94cf4bffda